# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 922e9ee6963ed3a2d1024b65da0f565ab1e63ea04593540552519c54255a16d2457d410ef19308aabe7595b70fb6f378cceee34e21e87403c3da4b4c02ba428e

test:
  secret_key_base: 6469be0080baa10cb809c9915f2184520f24eb5495d44265409c78d9cb4275815b581613afd6a8f976e0575937b2d87a34ba3dea13ddecdb49bb74c1abd7bbb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
